-- supabase/seed.sql
-- Run this AFTER applying migrations.
-- Idempotent: TRUNCATE ensures clean state on re-run.

TRUNCATE public.dog_parks CASCADE;

INSERT INTO public.dog_parks (
  name, address, city, state, zip_code,
  latitude, longitude, acres, size_label,
  is_fenced, has_small_dog_area, has_water_station, has_lighting,
  has_parking, has_restrooms, has_benches_shade, is_leash_free,
  hours, phone, website_url, notes
) VALUES
(
  'Philippe Park Dog Park',
  '2525 Philippe Pkwy',
  'Safety Harbor', 'FL', '34695',
  27.9884, -82.6935,
  NULL, 'Large',
  TRUE, TRUE, TRUE, FALSE,
  TRUE, TRUE, TRUE, TRUE,
  'Sunrise to Sunset',
  '(727) 669-1947',
  'https://www.pinellascounty.org/park/24_Philippe.htm',
  'Located within Philippe Park. Separate large and small dog areas.'
),
(
  'Largo Central Park Dog Run',
  '101 Central Park Dr',
  'Largo', 'FL', '33771',
  27.9094, -82.7879,
  2.0, 'Medium',
  TRUE, TRUE, TRUE, TRUE,
  TRUE, TRUE, TRUE, TRUE,
  'Sunrise to Sunset',
  '(727) 587-6740',
  'https://www.largo.com/government/departments/parks_recreation/',
  'Lighted facility within Largo Central Park. Separate small and large dog sections.'
),
(
  'Seminole City Park Dog Park',
  '7464 Ridge Rd',
  'Seminole', 'FL', '33776',
  27.8446, -82.7840,
  1.5, 'Medium',
  TRUE, TRUE, TRUE, FALSE,
  TRUE, FALSE, TRUE, TRUE,
  'Sunrise to Sunset',
  '(727) 391-0204',
  'https://www.myseminole.com/parks/',
  'Fenced dog park within Seminole City Park.'
),
(
  'Del Oro Park Dog Park',
  '200 San Salvador St',
  'Dunedin', 'FL', '34698',
  28.0219, -82.7745,
  1.0, 'Small',
  TRUE, FALSE, TRUE, FALSE,
  TRUE, FALSE, TRUE, TRUE,
  'Sunrise to Sunset',
  '(727) 298-3220',
  'https://www.dunedinfl.net/parks/',
  'Small fenced dog park in Del Oro Park near the Pinellas Trail.'
),
(
  'Cliff Stephens Park Dog Park',
  '1655 S Belcher Rd',
  'Clearwater', 'FL', '33764',
  27.9394, -82.7461,
  2.0, 'Large',
  TRUE, TRUE, TRUE, TRUE,
  TRUE, TRUE, TRUE, TRUE,
  'Sunrise to Sunset',
  '(727) 562-4800',
  'https://www.myclearwater.com/government/city-departments/parks-recreation/parks-facilities/parks/cliff-stephens-park',
  'Large lighted facility with separate areas for large and small dogs.'
),
(
  'Crest Lake Park Dog Park',
  '301 Lakeview Rd',
  'Clearwater', 'FL', '33756',
  27.9638, -82.7998,
  1.0, 'Medium',
  TRUE, FALSE, TRUE, FALSE,
  TRUE, FALSE, TRUE, TRUE,
  'Sunrise to Sunset',
  '(727) 562-4800',
  'https://www.myclearwater.com/government/city-departments/parks-recreation/parks-facilities/parks/crest-lake-park',
  'Dog park within Crest Lake Park near downtown Clearwater.'
),
(
  'Toytown Dog Park',
  '4th St N & 38th Ave N',
  'St. Petersburg', 'FL', '33703',
  27.8012, -82.6509,
  1.5, 'Medium',
  TRUE, TRUE, TRUE, FALSE,
  TRUE, FALSE, TRUE, TRUE,
  'Sunrise to Sunset',
  '(727) 893-7441',
  'https://www.stpete.org/recreation/parks/toytown_park.php',
  'Popular St. Pete dog park with separate sections for large and small dogs.'
),
(
  'Abercrombie Park Dog Park',
  '6979 54th Ave N',
  'St. Petersburg', 'FL', '33709',
  27.8291, -82.7418,
  1.0, 'Small',
  TRUE, FALSE, TRUE, FALSE,
  TRUE, FALSE, FALSE, TRUE,
  'Sunrise to Sunset',
  '(727) 893-7441',
  'https://www.stpete.org/recreation/parks/',
  'Small neighborhood dog park in northwest St. Petersburg.'
),
(
  'Crescent Lake Dog Park',
  '1320 5th St N',
  'St. Petersburg', 'FL', '33701',
  27.7889, -82.6501,
  1.5, 'Medium',
  TRUE, TRUE, TRUE, FALSE,
  TRUE, TRUE, TRUE, TRUE,
  'Sunrise to Sunset',
  '(727) 893-7441',
  'https://www.stpete.org/recreation/parks/crescent_lake_park.php',
  'Popular dog park near downtown St. Pete with large and small dog areas.'
),
(
  'North Shore Dog Park',
  '901 N Shore Dr NE',
  'St. Petersburg', 'FL', '33701',
  27.7862, -82.6319,
  1.0, 'Medium',
  TRUE, FALSE, TRUE, FALSE,
  TRUE, FALSE, TRUE, TRUE,
  'Sunrise to Sunset',
  '(727) 893-7441',
  'https://www.stpete.org/recreation/parks/north_shore.php',
  'Waterfront dog park along Tampa Bay in the North Shore district.'
),
(
  'Vinoy Dog Park',
  '701 Bayshore Dr NE',
  'St. Petersburg', 'FL', '33701',
  27.7790, -82.6286,
  0.5, 'Small',
  TRUE, FALSE, TRUE, FALSE,
  TRUE, FALSE, FALSE, TRUE,
  'Sunrise to Sunset',
  '(727) 893-7441',
  'https://www.stpete.org/recreation/parks/vinoy_park.php',
  'Small dog park within Vinoy Park with waterfront views.'
),
(
  'Shore Acres Dog Park',
  '4230 Shore Acres Blvd NE',
  'St. Petersburg', 'FL', '33703',
  27.8113, -82.6142,
  1.0, 'Medium',
  TRUE, FALSE, TRUE, FALSE,
  TRUE, FALSE, TRUE, TRUE,
  'Sunrise to Sunset',
  '(727) 893-7441',
  'https://www.stpete.org/recreation/parks/',
  'Neighborhood dog park in the Shore Acres area of St. Petersburg.'
),
(
  'Campbell Park Dog Park',
  '601 14th St S',
  'St. Petersburg', 'FL', '33701',
  27.7541, -82.6560,
  1.0, 'Medium',
  TRUE, TRUE, TRUE, FALSE,
  TRUE, TRUE, TRUE, TRUE,
  'Sunrise to Sunset',
  '(727) 893-7441',
  'https://www.stpete.org/recreation/parks/',
  'Dog park with large and small dog areas in south St. Petersburg.'
),
(
  'Lake Vista Dog Park',
  '1401 62nd Ave S',
  'St. Petersburg', 'FL', '33705',
  27.7252, -82.6680,
  1.5, 'Medium',
  TRUE, TRUE, TRUE, TRUE,
  TRUE, TRUE, TRUE, TRUE,
  'Sunrise to Sunset',
  '(727) 893-7441',
  'https://www.stpete.org/recreation/parks/lake_vista_park.php',
  'Lighted dog park with separate small and large dog areas in south St. Pete.'
),
(
  'Walter Fuller Dog Park',
  '7891 26th Ave N',
  'St. Petersburg', 'FL', '33710',
  27.8042, -82.7229,
  2.0, 'Large',
  TRUE, TRUE, TRUE, TRUE,
  TRUE, TRUE, TRUE, TRUE,
  'Sunrise to Sunset',
  '(727) 893-7441',
  'https://www.stpete.org/recreation/parks/walter_fuller_park.php',
  'One of the largest dog parks in St. Pete with excellent amenities.'
),
(
  'Bartlett Dog Park',
  '2000 Bartlett Park Dr N',
  'St. Petersburg', 'FL', '33713',
  27.7895, -82.6922,
  1.5, 'Medium',
  TRUE, TRUE, TRUE, FALSE,
  TRUE, FALSE, TRUE, TRUE,
  'Sunrise to Sunset',
  '(727) 893-7441',
  'https://www.stpete.org/recreation/parks/',
  'Dog park with large and small dog sections near central St. Petersburg.'
),
(
  'John Chesnut Sr. Park Dog Area',
  '2200 East Lake Rd',
  'Palm Harbor', 'FL', '34685',
  28.0827, -82.6894,
  2.0, 'Large',
  TRUE, TRUE, TRUE, FALSE,
  TRUE, TRUE, TRUE, TRUE,
  'Sunrise to Sunset',
  '(727) 669-1947',
  'https://www.pinellascounty.org/park/14_JohnChesnut.htm',
  'Large county park dog area with separate sections. Beautiful natural setting.'
),
(
  'Anderson Park Dog Area',
  '39699 US Hwy 19 N',
  'Tarpon Springs', 'FL', '34689',
  28.1411, -82.7528,
  1.5, 'Medium',
  TRUE, FALSE, TRUE, FALSE,
  TRUE, TRUE, TRUE, TRUE,
  'Sunrise to Sunset',
  '(727) 669-1947',
  'https://www.pinellascounty.org/park/04_Anderson.htm',
  'County park dog area in north Pinellas near Lake Tarpon.'
),
(
  'Wall Springs Park Dog Area',
  '3725 De Soto Blvd',
  'Palm Harbor', 'FL', '34683',
  28.0633, -82.7369,
  1.0, 'Medium',
  TRUE, FALSE, TRUE, FALSE,
  TRUE, FALSE, TRUE, TRUE,
  'Sunrise to Sunset',
  '(727) 669-1947',
  'https://www.pinellascounty.org/park/32_WallSprings.htm',
  'Dog area within Wall Springs Park near the Gulf coast.'
),
(
  'Ream Wilson Clearwater Trail Dog Area',
  '2176 Drew St',
  'Clearwater', 'FL', '33765',
  27.9722, -82.7703,
  0.5, 'Small',
  TRUE, FALSE, TRUE, FALSE,
  TRUE, FALSE, FALSE, TRUE,
  'Sunrise to Sunset',
  '(727) 562-4800',
  'https://www.myclearwater.com/government/city-departments/parks-recreation/trails',
  'Small designated off-leash area along the Ream Wilson Trail.'
),
(
  'Redington Beach Dog-Friendly Area',
  '17011 Gulf Blvd',
  'Redington Beach', 'FL', '33708',
  27.8107, -82.8147,
  NULL, 'Medium',
  FALSE, FALSE, FALSE, FALSE,
  TRUE, FALSE, FALSE, TRUE,
  'Sunrise to Sunset (seasonal restrictions may apply)',
  NULL,
  'https://www.redingtonbeachfl.gov/',
  'Designated dog-friendly beach area. Check local ordinances for seasonal restrictions.'
),
(
  'Fossil Park Dog Park',
  '7507 Ulmerton Rd',
  'Largo', 'FL', '33771',
  27.8762, -82.7510,
  2.0, 'Large',
  TRUE, TRUE, TRUE, TRUE,
  TRUE, TRUE, TRUE, TRUE,
  'Sunrise to Sunset',
  '(727) 587-6740',
  'https://www.largo.com/government/departments/parks_recreation/',
  'Spacious lighted dog park with excellent amenities in central Largo.'
),
(
  'Pinellas Park Dog Park',
  '5851 78th Ave N',
  'Pinellas Park', 'FL', '33781',
  27.8445, -82.7003,
  1.5, 'Medium',
  TRUE, TRUE, TRUE, FALSE,
  TRUE, FALSE, TRUE, TRUE,
  'Sunrise to Sunset',
  '(727) 541-0666',
  'https://www.pinellaspark.com/parks/',
  'Community dog park with separate large and small dog sections.'
);

INSERT INTO dog_parks (
  name, address, city, state, zip_code,
  latitude, longitude,
  acres, size_label,
  is_fenced, has_small_dog_area, has_water_station, has_lighting,
  has_parking, has_restrooms, has_benches_shade, is_leash_free,
  hours, phone, website_url, notes
) VALUES (
  'Walsingham Park Dog Run',
  '12615 102nd Ave N',
  'Largo',
  'FL',
  '33778',
  27.87669,
  -82.80816,
  3.0,
  'Large',
  true,
  true,
  false,
  false,
  true,
  true,
  true,
  true,
  '7:00 AM to Sunset',
  '(727) 549-6142',
  'https://pinellas.gov/parks/walsingham-park/',
  'Three fenced runs (two large-dog, one small-dog) overlooking Walsingham Lake. Part of a 350-acre county park with 6 miles of trails.'
);
